### ISSUE TITLE
Remove usage of service keys

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/eng-pipes#633]
Instead of service keys, let's use workload identity for better security for our bot.
```[tasklist]
### Tasks
- [x] Create a GCP service account in the security-as-code repo to be used by OIDC (https://github.com/getsentry/security-as-code/pull/384)
- [x] Grant the service account access to deploy Cloud Run services on the target GCP project (`roles/run.developer` or `role/run.admin` which ever is least privilege for the requirements)
- [x] Update `.github/workflows/ci.yml` to use Google's "keyless" auth GHA (https://github.com/getsentry/eng-pipes/pull/647)
- [x] Create and assign a dedicated service account for the Cloud Run service to run-as (https://github.com/getsentry/ops/pull/9016)
- [x] Grant the service account access to read/write/run jobs from google BigQuery (https://github.com/getsentry/ops/pull/9121)
```
